// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrioridadesLor.DAL;

#nullable disable

namespace PrioridadesLor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240120164853_Cliente")]
    partial class Cliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("PrioridadesLor.Models.Clientes", b =>
                {
                    b.Property<int>("ClientesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CelularClientes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionClientes")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailClientes")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombresClientes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RNC")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoClientes")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientesID");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("PrioridadesLor.Models.Prioridades", b =>
                {
                    b.Property<int>("IdPrioridades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasCompromiso")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPrioridades");

                    b.ToTable("prioridades");
                });
#pragma warning restore 612, 618
        }
    }
}
