// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrioridadesLor.DAL;

#nullable disable

namespace PrioridadesLor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20240205051655_Clientes")]
    partial class Clientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("PrioridadesLor.Models.Clientes", b =>
                {
                    b.Property<int>("ClientesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CelularClientes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DireccionClientes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailClientes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombresClientes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoClientes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientesID");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("PrioridadesLor.Models.Prioridades", b =>
                {
                    b.Property<int>("IdPrioridades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiasCompromiso")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdPrioridades");

                    b.ToTable("prioridades");
                });

            modelBuilder.Entity("PrioridadesLor.Models.Sistemas", b =>
                {
                    b.Property<int>("SistemasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SistemasNombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SistemasId");

                    b.ToTable("sistemas");
                });

            modelBuilder.Entity("PrioridadesLor.Models.Tickets", b =>
                {
                    b.Property<int>("TicketsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrioridadesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SistemasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolicitadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TicketsId");

                    b.ToTable("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
